server:
  applicationConnectors:
  - type: http
    port: 50050
  adminConnectors:
  - type: http
    port: 50150

inventoryPort: 60001
paymentsPort: 50063
stylingPort: 50051
deliveryPort: 50054

inventoryHost: "localhost"
paymentsHost: "localhost"
stylingHost: "localhost"
deliveryHost: "localhost"

applicationTagsYamlFile: "./shopping/applicationTags.yaml"
wfReportingConfigYamlFile: "./wfReportingConfig.yaml"