apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: shopping
    shard: blue
  name: shopping-blue
  namespace: tacocat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacocat
      service: shopping
      shard: blue
  template:
    metadata:
      labels:
        app: tacocat
        service: shopping
        shard: blue
    spec:
      containers:
      - name: shopping
        image: harbor.vmw.binbytes.io/demo-app/shopping:latest
        imagePullPolicy: Always
        command:
          - "/cnb/process/web"
          - "server"
          - "/conf/shopping-app.yaml"
        ports:
        - containerPort: 50050
          name: application
          protocol: TCP
        - containerPort: 50150
          name: admin
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        resources:
          # limits:
          #   memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: shopping
    shard: green
  name: shopping-green
  namespace: tacocat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacocat
      service: shopping
      shard: green
  template:
    metadata:
      labels:
        app: tacocat
        service: shopping
        shard: green
    spec:
      containers:
        - name: shopping
          image: harbor.vmw.binbytes.io/demo-app/shopping:latest
          imagePullPolicy: Always
          command:
            # - "java"
            # - "-jar"
            # - "/shopping.jar"
            - "/cnb/process/web"
            - "server"
            - "/conf/shopping-app.yaml"
          ports:
            - containerPort: 50050
              name: application
              protocol: TCP
            - containerPort: 50150
              name: admin
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
          resources:
            # limits:
            #   memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744

